name: build
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Build Nagios Plugin
        working-directory: integrations/nagios/check_wp_status
        run: |
          GOOS=linux   GOARCH=amd64 go build -o ../../../dist/check_wp_status
          GOOS=darwin  GOARCH=amd64 go build -o ../../../dist/check_wp_status-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o ../../../dist/check_wp_status-windows-amd64.exe

      - name: Build Munin Plugin
        working-directory: integrations/munin/wp_status
        run: |
          GOOS=linux   GOARCH=amd64 go build -o ../../../dist/wp_status
          GOOS=darwin  GOARCH=amd64 go build -o ../../../dist/wp_status-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o ../../../dist/wp_status-windows-amd64.exe

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: 
            dist/check_wp_status
            dist/check_wp_status-darwin-amd64
            dist/check_wp_status-windows-amd64.exe
            dist/wp_status
            dist/wp_status-darwin-amd64
            dist/wp_status-windows-amd64.exe
          asset_name: ${{ github.ref_name }}-asset-{{ runner.os }}-{{ runner.arch }}.tar.gz
          tag: ${{ github.ref_name }}
